### ISSUE TITLE
How to get the `status-line`?

### ISSUE THREAD

**Issue by thyeun** [crivotz/nv-ide#18]
@crivotz Sorry for asking, how i can get the ```status-line``` as per your ```readme.md``` images.

your nv-ide image
![2022-06-30T22:10:27,892149674+08:00](https://user-images.githubusercontent.com/1939446/176699119-f6070c60-29b5-4cad-b8ce-37aca28a40a7.png)

my nv-ide images
![2022-06-30T22:08:39,946461226+08:00](https://user-images.githubusercontent.com/1939446/176698712-89f6435e-d583-4643-987d-1ff199b484a5.png)

How can i turn it on?

**Comment by crivotz** [comment]
looking at it this way the only thing you are currently missing is a font that handles ligatures the triangle you see is nothing more than the representation of `|>` with ligatures.

The part at the bottom where it says FTB is TMUX

**Comment by thyeun** [comment]
Sad, both i got also not support (xfce4-terminal and alacritty) :((

**Comment by crivotz** [comment]
Sorry, you can the chars `|>` inside feline configuration file `feline.lua`
In the meanwhile I updated readme with ligatures information

**Comment by thyeun** [comment]
Ok, noted.

One more question the line after ```NV-IDE```, my one still missing ```FTB |> 1 |> VIM .....```, it is also related with the font (ligatures)?

**Comment by crivotz** [comment]
It's TMUX, not related to neovim.

**Comment by thyeun** [comment]
Ok, noted, will close this as i done replace all the glyph :)
